name: Issue Duplicator

on:
  issue_comment:
    types: [created, edited]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: mashabow/issue-duplicator-action@v1
        with:
          github-token: ${{ secrets.ISSUE_DUPLICATOR_PAT }}
